import { v } from "convex/values";
import { internalAction } from "./_generated/server";

/**
 * Real weather, from Open-Meteo.
 *
 * Two different questions need two different datasets, and both are live:
 *
 *  - "what is it doing there now / this fortnight" → the forecast endpoint,
 *  - "which month should I go" → the ERA5 archive, aggregated into monthly
 *    normals over the last three complete years.
 *
 * Nothing here is generated by a model. The AI layer reads these numbers and
 * explains them; it is not allowed to make them up.
 */

const FORECAST = "https://api.open-meteo.com/v1/forecast";
const ARCHIVE = "https://archive-api.open-meteo.com/v1/archive";

export const WEATHER_SOURCE = "Open-Meteo (forecast + ERA5 archive)";

export type DayWeather = {
  date: string;
  code: number;
  label: string;
  maxC: number;
  minC: number;
  rainMm: number;
};

export type MonthClimate = {
  month: string;
  /** 1 = January. */
  index: number;
  avgMaxC: number;
  avgMinC: number;
  avgRainMm: number;
  /** How comfortable the month looks for walking around, 0–1. */
  comfort: number;
  note: string;
};

export type WeatherPanel = {
  source: string;
  available: boolean;
  reason?: string;
  now?: { maxC: number; minC: number; rainMm: number; label: string };
  days: DayWeather[];
  months: MonthClimate[];
  years: number[];
};

/** WMO weather codes, as Open-Meteo reports them. */
const CODES: Record<number, string> = {
  0: "Clear",
  1: "Mostly clear",
  2: "Partly cloudy",
  3: "Overcast",
  45: "Fog",
  48: "Freezing fog",
  51: "Light drizzle",
  53: "Drizzle",
  55: "Heavy drizzle",
  61: "Light rain",
  63: "Rain",
  65: "Heavy rain",
  66: "Freezing rain",
  67: "Freezing rain",
  71: "Light snow",
  73: "Snow",
  75: "Heavy snow",
  77: "Snow grains",
  80: "Rain showers",
  81: "Rain showers",
  82: "Violent showers",
  85: "Snow showers",
  86: "Snow showers",
  95: "Thunderstorms",
  96: "Thunderstorms",
  99: "Thunderstorms",
};

function labelFor(code: number): string {
  return CODES[code] ?? "Mixed weather";
}

/**
 * Comfort is a plain, explainable blend: mild days score high, heavy rain and
 * heat or cold score low. It is deliberately not a "best month" verdict — the
 * personalised judgement belongs to the layer that knows the person.
 */
function comfortFor(maxC: number, minC: number, rainMm: number): number {
  const rain = Math.max(0, 1 - rainMm / 140);
  const heat = maxC <= 28 ? 1 : Math.max(0, 1 - (maxC - 28) / 14);
  const cold = minC >= 4 ? 1 : Math.max(0, 1 - (4 - minC) / 16);
  return Number((rain * 0.45 + heat * 0.3 + cold * 0.25).toFixed(3));
}

function monthName(index: number): string {
  return new Date(Date.UTC(2024, index, 1)).toLocaleString("en", { month: "long" });
}

type Daily = {
  time?: string[];
  weather_code?: number[];
  temperature_2m_max?: number[];
  temperature_2m_min?: number[];
  precipitation_sum?: number[];
};

/** Everything the interface needs about a point on the map, live. */
export const panel = internalAction({
  args: { lat: v.number(), lng: v.number() },
  handler: async (_ctx, args): Promise<WeatherPanel> => {
    const lat = Number(args.lat.toFixed(4));
    const lng = Number(args.lng.toFixed(4));
    const base: WeatherPanel = { source: WEATHER_SOURCE, available: false, days: [], months: [], years: [] };

    const forecastUrl =
      `${FORECAST}?latitude=${lat}&longitude=${lng}` +
      "&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_sum" +
      "&current=temperature_2m,weather_code&forecast_days=16&timezone=auto";

    // Three complete years of history, so monthly normals are not a guess.
    const thisYear = new Date().getUTCFullYear();
    const endYear = thisYear - 1;
    const startYear = endYear - 2;
    const archiveUrl =
      `${ARCHIVE}?latitude=${lat}&longitude=${lng}` +
      `&start_date=${startYear}-01-01&end_date=${endYear}-12-31` +
      "&daily=temperature_2m_max,temperature_2m_min,precipitation_sum&timezone=auto";

    const [forecastRes, archiveRes] = await Promise.all([
      fetch(forecastUrl).catch(() => null),
      fetch(archiveUrl).catch(() => null),
    ]);

    if (!forecastRes?.ok && !archiveRes?.ok) {
      return { ...base, reason: "Weather could not be reached just now." };
    }

    const days: DayWeather[] = [];
    let now: WeatherPanel["now"];

    if (forecastRes?.ok) {
      const body = (await forecastRes.json()) as {
        daily?: Daily;
        current?: { temperature_2m?: number; weather_code?: number };
      };
      const daily = body.daily ?? {};
      const times = daily.time ?? [];
      for (let index = 0; index < times.length; index += 1) {
        const code = daily.weather_code?.[index] ?? 0;
        days.push({
          date: times[index],
          code,
          label: labelFor(code),
          maxC: Math.round(daily.temperature_2m_max?.[index] ?? 0),
          minC: Math.round(daily.temperature_2m_min?.[index] ?? 0),
          rainMm: Number((daily.precipitation_sum?.[index] ?? 0).toFixed(1)),
        });
      }
      const first = days[0];
      if (first) {
        now = {
          maxC: first.maxC,
          minC: first.minC,
          rainMm: first.rainMm,
          label: labelFor(body.current?.weather_code ?? first.code),
        };
      }
    }

    const months: MonthClimate[] = [];
    if (archiveRes?.ok) {
      const body = (await archiveRes.json()) as { daily?: Daily };
      const daily = body.daily ?? {};
      const times = daily.time ?? [];
      const buckets = Array.from({ length: 12 }, () => ({ max: 0, min: 0, rain: 0, count: 0 }));
      for (let index = 0; index < times.length; index += 1) {
        const month = Number(times[index].slice(5, 7)) - 1;
        if (month < 0 || month > 11) continue;
        const bucket = buckets[month];
        bucket.max += daily.temperature_2m_max?.[index] ?? 0;
        bucket.min += daily.temperature_2m_min?.[index] ?? 0;
        bucket.rain += daily.precipitation_sum?.[index] ?? 0;
        bucket.count += 1;
      }
      buckets.forEach((bucket, index) => {
        if (bucket.count === 0) return;
        const sample = Math.max(bucket.count, 1);
        const avgMaxC = Number((bucket.max / sample).toFixed(1));
        const avgMinC = Number((bucket.min / sample).toFixed(1));
        // The archive gives a daily total, so the month figure is the average
        // day's rain spread over a 30-day month — not three years added up.
        const avgRainMm = Number(((bucket.rain / sample) * 30).toFixed(1));
        months.push({
          month: monthName(index),
          index: index + 1,
          avgMaxC,
          avgMinC,
          avgRainMm,
          comfort: comfortFor(avgMaxC, avgMinC, avgRainMm),
          note: `${avgMaxC}°C daytime, ${avgMinC}°C at night, ${Math.round(avgRainMm)} mm of rain across the month`,
        });
      });
    }

    if (days.length === 0 && months.length === 0) {
      return { ...base, reason: "Weather could not be reached just now." };
    }

    return {
      ...base,
      available: true,
      now,
      days,
      months,
      years: months.length > 0 ? [startYear, endYear] : [],
    };
  },
});
